import type { Metadata } from "next";
import "./globals.css";
import { workSans } from "./fonts";
import "easymde/dist/easymde.min.css";
import { Analytics } from "@vercel/analytics/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} antialiased`}
      >
        <Analytics/>
        {children}
      </body>
    </html>
  );
}
